name: build
on: [push, pull_request]
jobs:
  windows:
    timeout-minutes: 60
    runs-on: windows-latest

    strategy:
      matrix:
        generator: [Visual Studio 16 2019]
        mode: [-DBUILD_UVW_LIBS=ON, -DBUILD_UVW_LIBS=OFF]

    steps:
    - uses: actions/checkout@v1
    - name: Compile tests
      working-directory: build
      run: |
        cmake ${{ matrix.mode }} -DBUILD_TESTING=ON -Dlibuv_buildtests=OFF -DCMAKE_CXX_FLAGS=/W1 -G"${{ matrix.generator }}" ..
        cmake --build . --target async idle -j 4
